### PR TITLE
Preview images in their example folder and on the main README

### PR DESCRIPTION
**Pull request by echarles**
This implements #43 and addresses one comment I made in #40 

@jtpio @fcollonval

### CODE REVIEW

**Comment by fcollonval** [comment]
I really like the idea of having the picture at the beginning of the example READMEs.

But I find the root README harder to grasp with all the illustrations. In particular, we are loosing the  global overview of what is available compared to the actual `toc` like approach.

**Comment by echarles** [comment]
@fcollonval I have added a very flat toc before the preview by extension point. This is also more inline with initial @jtpio intent written in #40. WDYT?

**Comment by fcollonval** [comment]
LGTM ! Thanks for adding the toc @echarles 

(Note: I took the liberty to correct the reference issue in your comment 😉 )

**Comment by echarles** [comment]
Thx @fcollonval. Just pushed 2 last changes: clickable images + link to skip the long and growing preview (for a developer who wants to know how to develop on the examples).

Let's wait a bit on @jtpio feedback before merging. LGTM.

**Comment by fcollonval** [comment]
> Let's wait a bit on @jtpio feedback before merging.

I agree

**Comment by jtpio** [comment]
Thanks @echarles, that looks great and addresses nicely #43!

And yes, keeping the TOC is important, and often requested in other discussions related to the documentation.

**Comment by echarles** [comment]
Conflict is resolved.

**Comment by echarles** [comment]
And toc/preview have now the new `state` example.

**Pull request merged**
