### PR TITLE
Use embedme

### LINKED ISSUE #20: Snippets from code
One of the hard part with examples is to maintain the snippets in README in sync with the testable code. Would it be interesting to use one of the following solutions (or another one - I looked quickly on the web for that problem)?

https://github.com/NativeScript/markdown-snippet-injector
https://github.com/zakhenry/embedme

### PR DESCRIPTION
**Pull request by fcollonval**
Embed snippet in README directly from code file

Fixes #20

### CODE REVIEW

**Comment by fcollonval** [comment]
@jtpio @echarles I tested the tool `embedme` on the hello world example (see https://github.com/jtpio/jupyterlab-extension-examples/pull/27/commits/37e4ff79ac5508f1e2626be9abf520670f0e3a18)

What do you think?

**Comment by jtpio** [comment]
Thanks @fcollonval for trying it out.

What happens if we modify the source and then run `embedme` again? We still need to update the lines in `src/index.ts#L1-L4` for example? (which is still better than copy pasting the code!)

**Comment by echarles** [comment]
I am in favor of such generation toolkits to avoid copy/paste and keep the doc in sync with src.

To expand on @jtpio question, what if we add lines prior to the targeted source block and run `embedme` again. I guess the generated block will not be correct. Is it possible to define a block based on annotations in comments?

**Comment by fcollonval** [comment]
> What happens if we modify the source and then run `embedme` again? We still need to update the lines in `src/index.ts#L1-L4`? (which is still better than copy pasting the code!)

> To expand on @jtpio question, what if we add lines prior to the targeted source block and run `embedme` again. I guess the generated block will not be correct. Is it possible to define a block based on annotations in comments?

I demonstrated a case of modification of the code without rerunning `embedme` (see https://github.com/jtpio/jupyterlab-extension-examples/pull/27/checks?check_run_id=306943199). By executing a verification in the CI, the dev can see that something needs to be changed. But indeed, by simply executing `embedme`, the snippets will be wrong without changing the lines range.

The other tool I found (https://github.com/NativeScript/markdown-snippet-injector) work using annotations in comments inside the source files. Unfortunately it supports only CSS, TypeScript and XML file. This does not fit our need I think as we need JSON and Python too. Another disadvantage of that approach are the annotations them self. Will they increase readability for the newbies looking for help with these examples?

**Comment by jtpio** [comment]
> I demonstrated a case of modification of the code without rerunning `embedme` (see https://github.com/jtpio/jupyterlab-extension-examples/pull/27/checks?check_run_id=306943199). By executing a verification in the CI, the dev can see that something needs to be changed. But indeed, by simply executing `embedme`, the snippets will be wrong without changing the lines range.

This is good. At least CI tells us if something needs to be changed.

> The other tool I found (https://github.com/NativeScript/markdown-snippet-injector) work using annotations in comments inside the source files. Unfortunately it supports only CSS, TypeScript and XML file. This does not fit our need I think as we need JSON and Python too. Another disadvantage of that approach are the annotations them self. Will they increase readability for the newbies looking for help with these examples?

Also not a big fan of having too many annotations in the source code itself (readability issues). `embedme` looks good so far so we can go for it and see how it goes.

**Comment by echarles** [comment]
> This is good. At least CI tells us if something needs to be changed.

CI fails with a clear message so we are safe here: the developer can change his docs.

> Also not a big fan of having too many annotations in the source code itself (readability issues). embedme looks good so far so we can go for it and see how it goes.

+1

**Comment by fcollonval** [comment]
I extended the use of `embedme` to all existing README files. This is ready for review.

**Comment by jtpio** [comment]
Thanks @fcollonval!

**Comment by echarles** [comment]
The merge has given a false negative on CI for the signals example giving a red badge on the home README. GitHub does not seem to support manual build trigger so I have createe #33 to confirm this was a flaky state. Not sure how flaky this will be in the future. 

Thx @fcollonval

**Pull request merged**
