### PR TITLE
React example

### LINKED ISSUE #8: Add React example
React is already used in some of the examples, but we should have an example that explicitly says `react` in its title. Maybe just called `react` then.

It would be using version `16.8.4+` with hooks.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #8.

image

### TODO

- [x] Add React icon
- [x] Add launcher item
- [x] Add new example to CI
- [x] Implement the example (increment counter on click for example)
- [x] Add instructions to the README
- [x] Add screencast to show how to use the React Tools to inspect components
- [x] ~Mention `UseSignal`?~ -> can be done in a different example

### CODE REVIEW

**Comment by jtpio** [comment]
cc @echarles 

This adds a very simple example that uses the `ReactWidget` wrapper from `@jupyterlab/apputils`.

For the instructions, there isn't much, but there are now some screencasts to at least give an idea of what the extension looks like.

I'm wondering whether it would be useful to do more narrative and explain each part of the extension. In any case this is something we could iterate on.

**Comment by echarles** [comment]
Great job @jtpio. Tested and works as expected.

Screencast is very useful for newcomers. We can iterate later on the explanations in function of the other examples.

2 questions which are applicable also to the other examples:

- Should the class names be set in constants? I think I have read some time ago that jlab moved away from that in favor of simple strings if they are used only once I guess (better to be discussed in #4).
- I have a `[W 10:12:19.264 LabApp] Failed to fetch package metadata for '@jupyterlab-examples/react-widget': <HTTPError 404: 'Not Found'>` - No side effect. Not sure if this is also the case for other extensions.

Apart from that, LGTM

**Comment by jtpio** [comment]
Thanks @echarles for reviewing.

> * Should the class names be set in constants? I think I have read some time ago that jlab moved away from that in favor of simple strings if they are used only once I guess (better to be discussed in #4).

Good question. The current JLab code base has some CSS classes set in constants. But here we can indeed do without as they are used only once.

I also took the opportunity to add some docstrings to follow #4.

>  * I have a `[W 10:12:19.264 LabApp] Failed to fetch package metadata for '@jupyterlab-examples/react-widget': <HTTPError 404: 'Not Found'>` - No side effect. Not sure if this is also the case for other extensions.

This is because the packages have not been published on npm:

https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L2162-L2164

As a side note I created the [jupyterlab-examples](https://www.npmjs.com/org/jupyterlab-examples) organization on npm, in case we want to publish those examples (this could be automated with CI).

**Comment by echarles** [comment]
closes #8

**Pull request merged**
