### PR TITLE
Use the new style inclusion

### PR DESCRIPTION
**Pull request by fcollonval**

### CODE REVIEW

**Comment by jtpio** [comment]
Looks good, thanks!

It looks like we could also remove it from the (new) react widget example: https://github.com/jtpio/jupyterlab-extension-examples/blob/86545aa637715a3fc9afe608ccde2371c7ff7e76/react/react-widget/src/index.ts#L11

**Comment by echarles** [comment]
I am ok with the proposed changes. It would be good to write a note on how to configure is multiple css files are used (I see the `style` key in `package.json` allows only one css file definition).

**Comment by echarles** [comment]
At some point, we should at least have an examples that shows how to import css files from typescript. This could be a dedicated examples exploring also SCSS, SASS... loading.

**Comment by fcollonval** [comment]
> It looks like we could also remove it from the (new) react widget example:
> 
> https://github.com/jtpio/jupyterlab-extension-examples/blob/86545aa637715a3fc9afe608ccde2371c7ff7e76/react/react-widget/src/index.ts#L11

Thx @jtpio for catching that.

**Pull request merged**
