### PR TITLE
Switch to eslint

### LINKED ISSUE #49: Switch from tslint to eslint
`tslint` is being deprecated. We should switch to `eslint`.

References:
https://github.com/typescript-eslint/tslint-to-eslint-config
https://github.com/typescript-eslint/typescript-eslint

### PR DESCRIPTION
**Pull request by fcollonval**
Fix #49

### CODE REVIEW

**Comment by fcollonval** [comment]
@jtpio 

It looks that Jason tunes very few rules. For now, I use tslint to eslint converter to generate the rules list. Should we rather use the same short list of ipywidgets + the recommended sets of rules.

```json
  "rules": {
    "@typescript-eslint/interface-name-prefix": [
      "error", { "prefixWithI": "always" }
    ],
    "@typescript-eslint/no-unused-vars": [
      "warn", { "args": "none" }
    ],
    "@typescript-eslint/no-use-before-define": "off",
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-namespace": "off"
  },
```

**Comment by jtpio** [comment]
Thanks @fcollonval for this!

> Should we rather use the same short list of ipywidgets + the recommended sets of rules.

If it considerably simplifies the config, it would definitely be something worth considering.

**Comment by fcollonval** [comment]
@jtpio @echarles 
This is ready for review - BTW I just discovered that GitHub is displaying eslint feedback directly in the code. This is amazing.

**Comment by jtpio** [comment]
Thanks a lot @fcollonval, this looks really good. Will check it more in details later today.

It will also help keep a consistent style across all the examples (https://github.com/jtpio/jupyterlab-extension-examples/issues/4).

> BTW I just discovered that GitHub is displaying eslint feedback directly in the code. This is amazing.

Looks like there are a couple of warnings :)

**Comment by fcollonval** [comment]
@jtpio Oh ja, I forgot to raise that question. Do we want to check code documentation through JSDoc or not?

**Comment by echarles** [comment]
> @jtpio Oh ja, I forgot to raise that question. Do we want to check code documentation through JSDoc or not?

Why not but maybe part of a separated PR.

**Comment by jtpio** [comment]
Separate PR sounds good :+1:

**Pull request merged**
