### PR TITLE
Use local tsconfig

### LINKED ISSUE #30: tsconfig questions
Hey, I got two questions about the typescript configuration for the examples:

* We are not using the same options than the extension template, not the Jupyterlab core. Would it be better to use options as close as possible?
* Currently example tsconfig files point to a to level file. Would it be better to keep all the configuration in each example folder? That would allow interested people to start from a copy-paste of an example?

### PR DESCRIPTION
**Pull request by fcollonval**
Fix #30 

Question:
- Should we store a reference and compare to it?
- `tslint` uses a global `tsconfig` should we keep the current one or use a common one that we compare to the package ones?

### CODE REVIEW

**Comment by fcollonval** [comment]
@echarles @jtpio I let willing a difference to check the test is failing.

From the CI output, it is hard to figure out which file is erroneous. So it may be better to compare package tsconfig files one by one to a specific source of truth?

**Comment by jtpio** [comment]
Nice to see that CI was able to catch that.

Maybe we could make the hello world the reference, and add the CI check in each of the examples to compare itself against the hello world tsconfig (using the matrix)?

**Comment by fcollonval** [comment]
@jtpio if the error reporting at the package level as happend in the latest commit is ok. I'll correct the code and it will be good to go from my side.

**Comment by jtpio** [comment]
We get something like this:

image

Which looks good :+1: (like a regular diff)

**Comment by jtpio** [comment]
It looks like we need to keep the top-level `tsconfig-base.json` for the `tslint` script.

Otherwise we remove it and push the lint scripts down to the examples?

**Comment by fcollonval** [comment]
> Otherwise we remove it and push the lint scripts down to the examples?

Ja, I saw that. I don't know what is the best strategy. Either we let a base one that can be used as reference and we avoid the trouble to add `tslint` in each example. Or we put it down as you suggested.

@echarles what your opinion on that?

**Comment by echarles** [comment]
We could have:
- a base (or ref) tsconfig in the root folder that would be the reference
- a common tlslint that uses the base config
- each of the example duplicate the base (or ref) tsconfig
- CI checks all the example tsconfig against the base (or ref) tsconfig.

WDYT?

**Comment by fcollonval** [comment]
After some more testing, actually we cannot use a `tsconfig` at the root as reference. 
In the example folder, the `tsconfig` file specifies the source folder. If the root reference does that, `tslint` will not check the examples but only a `src` folder.

So we are left with two options:
- Set `tslint` at the example level
- Use a separate `tsconfig` at the root level for `tslint`

I prefer the first option. What about you?

**Comment by echarles** [comment]
I can buy the same tslint in each of the example folder (if this is what you mean with option 1) with CI enforcing the equality check.

**Comment by jtpio** [comment]
Setting `tslint` at the example level would also make it easier to copy / paste or bootstrap other extensions, and have linting support by default.

**Pull request merged**
